### ISSUE TITLE
pyopenjtalk安装不上一直报错

### ISSUE THREAD

**Issue by dwsxx1** [mhy9989/moevoice#1]
Building wheels for collected packages: pyopenjtalk
  Building wheel for pyopenjtalk (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyopenjtalk (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      running bdist_wheel
      running build
      running build_py
      -- Building version 0.2.0
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\pyopenjtalk
      copying pyopenjtalk\version.py -> build\lib.win-amd64-3.8\pyopenjtalk
      copying pyopenjtalk\__init__.py -> build\lib.win-amd64-3.8\pyopenjtalk
      creating build\lib.win-amd64-3.8\pyopenjtalk\htsvoice
      copying pyopenjtalk\htsvoice\LICENSE_mei_normal.htsvoice -> build\lib.win-amd64-3.8\pyopenjtalk\htsvoice
      copying pyopenjtalk\htsvoice\mei_normal.htsvoice -> build\lib.win-amd64-3.8\pyopenjtalk\htsvoice
      copying pyopenjtalk\htsvoice\README.md -> build\lib.win-amd64-3.8\pyopenjtalk\htsvoice
      running build_ext
      skipping 'pyopenjtalk\openjtalk.cpp' Cython extension (up-to-date)
      skipping 'pyopenjtalk\htsengine.cpp' Cython extension (up-to-date)
      building 'pyopenjtalk.openjtalk' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyopenjtalk
Failed to build pyopenjtalk
ERROR: Could not build wheels for pyopenjtalk, which is required to install pyproject.toml-based projects

**Comment by dwsxx1** [comment]
MSVC已安装

**Comment by mhy9989** [comment]
可以尝试安装pip install pyproject再安装pyopenjtalk
